services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: happy-db
      MONGO_INITDB_USERNAME: happy-user
      MONGO_INITDB_PASSWORD: happy-pass
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    networks:
      - workspace

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - workspace

networks:
  workspace:
